[workspace]
members = ["loader", "common", "plugin-spotify"]

[workspace.package]
version = "1.0.2"
authors = ["Shayne Hartford <shaybox@shaybox.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/ShayBox/VRC-OSC"
license = "MIT"

[workspace.dependencies]
abi_stable = { version = "0.10.4", default-features = false }
common = { path = "common" }
error-stack = "0.2.4"
plugin-spotify = { path = "plugin-spotify" }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
