[package]
name = "plugin-spotify"
description = "Sends the currently playing track from Spotify to the chatbox"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "spotify"
crate-type = ["cdylib"]

[dependencies]
abi_stable.workspace = true
common.workspace = true
error-stack.workspace = true
ferrispot = { version = "0.3.3", features = ["sync"] }
rosc.workspace = true
terminal-link = "0.1.0"
tiny_http = "0.12.0"
url = "2.3.1"
webbrowser = "0.8.2"
