on:
  release:
    types: [created]

jobs:
  release:
    env:
      SPOTIFY_CLIENT: ${{ secrets.SPOTIFY_CLIENT }}
      SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: i686-pc-windows-msvc
            os: windows-latest
          - target: i686-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: spotify-vrc-osc
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
